### ISSUE TITLE
Help page not formatted correctly with option 10

### ISSUE THREAD

**Issue by Chrysostomus** [Manjaro-Pek/pacli#19]
Choosing number+h prints help for that item correctly, but choosing 10 for help prints raw color codes around titles instead of coloring the output.

**Comment by papajoker** [comment]
after fetch and merge this master branch
no problem with 9h 10h "10 h" "10 -h" "10+h" or 11h, at home, titles are bold ...

a section must start with the characters *\* or !! directly followed by the number and one character space
the regex : 

```
/[\*\*?\!\!]${id} /
```

**Comment by Chrysostomus** [comment]
I don't have any problem with those either, they work as they should. Problem arises if I choose just "10" and press enter. I suspect it because the help page is piped into less.

**Comment by Chrysostomus** [comment]
I tried removing the pipe to less and adding read after the help_text function. That displays info properly. 

Is there some way to make this work with less, or should we just cat it?

**Comment by papajoker** [comment]
ok i have same problem with jwm !
just change the first line of help_text() and add -R

```
local id="${1:-0}" command="less -R"
```

ps: me i have `LESS = -R` in env ;)
Perhaps an environment variable to add to the iso Manjaro  because it seems normal that less can interpret the colors ?

Note with jvm pacli is unusable because the console default color is orange with BG red 13..18 :-1:

**Comment by Chrysostomus** [comment]
Tried the solution, worked right, implemented it. Thanks
