### ISSUE TITLE
Red option - foreground or background

### ISSUE THREAD

**Issue by Chrysostomus** [Manjaro-Pek/pacli#20]
I'd like to use red foreground instead of red background on risky options. It is more readable on most configs. Anybody object?

**Comment by excalibur1234** [comment]
as long as the dangerous/red options are still clearly visible, i do not have a problem with that.

i actually see another advantage of your proposed change: it would be easier to have a normal and red/dangerous option in one line.

**Comment by papajoker** [comment]
an idea (not sure)
show  section help before  run dangerous?

**Comment by excalibur1234** [comment]
i am skeptical. it is definitely great for beginners, but experienced users could feel patronized. pacli is aimed at experienced/intermediate users only.

the option being red should be warning enough.

if all of you guys like this idea, i recommend to implement it in the following form:
whenever a red option is chosen, the terminal gets cleared and the help of the red option is shown. the user has to press [ENTER] to continue.
This way, an experienced user can chose a red option and just press enter twice, because he already knows what the red option does.

**Comment by papajoker** [comment]
ok 
i make this help with press [Enter] for continue red command in new [branch help](https://github.com/papajoker/pacli/tree/help)
its easy to disable : 
- in code source (view var $PARAMS)
- pacli can use a local file `$HOME/.config/paclirc`
  set `helpred`=0

note: paclirc is ok for other user config ...

**Comment by excalibur1234** [comment]
looks like this issue is resolved.

i have added paclirc to the readme.md file.
